version: "3.9"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dot_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
